language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t tonymoney/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true tonymoney/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-1-147257209156"
  bucket_path: "docker"
  on:
    branch: master
access_key_id: $AWS_ACCESS_KEY
secret_access_key: $AWS_SECRET_KEY
