FROM node:16-alpine as builder

USER node
RUN mkdir -p /home/node/app
# WORKDIR '/app'
WORKDIR /home/node/app

COPY --chown=node:node ./package.json ./
# COPY package.json .
RUN npm install

COPY --chown=node:node ./ ./
#COPY . .

RUN npm run build

FROM nginx:latest

COPY --from=builder /home/node/app/build /usr/share/nginx/html

# STEP 1: Using the WSL terminal build your Docker image as you typically would:
# antoniodenaro@IAMHAPPY:~/frontend$ docker build .

